### PR TITLE
Fix get_from_tests run_command_in_container call

### PR DESCRIPTION
**Pull request by acrmp**
- The issue_gen.get_from_tests command was updated in cabec5da to read the test command timeout from the repo profile
- However the caller was not updated to pass the repo profile through

Fixes:

```
TypeError: run_command_in_container() missing 1 required positional argument: 'rp'
```

### CODE REVIEW

**Comment by acrmp** [comment]
The test failure here already exists on `main` and is fixed in #153.
